[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "chatterbot>=1.2.7",
    "chatterbot-corpus>=1.2.2",
    "flask>=3.1.1",
    "spacy>=3.8.7",
]
